Fix python-gdb.py didn't support new dict implementation.
